### ISSUE TITLE
Need some help as i am trying to work in connecting wiimote to android

### ISSUE THREAD

**Issue by He-maxed** [bskdany/AndroidBluetoothAutoPair#1]
https://github.com/timawesomeness/PairWiimote/
i'm rooted but i am facing socketconnect() error as the dev has abandoned this preoject i have no clue how to make it work with a12+ devices

**Comment by bskdany** [comment]
As much as I like to help you I haven't touched the android bluetooth functionality in years. And even if I fork the repo and give it a look I don't have a wii remote to test the app with. 
My speculation is that either the app broke because either the Wii firmware got updated or something changed in android 12 (or before that, idk which one did work), the latter is the most plausible imo.
I would love to help you but I don't have the hardware to do so, so it's up to you to figure this one out.

**Comment by He-maxed** [comment]
i have all hardware you need, can we connect and try it somehow?
if possible?

**Comment by bskdany** [comment]
I'm sorry but I have other things going on in life
